# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourierE2EApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CourierCore', '0.0.5'
  pod 'CourierMQTT', '0.0.5'
  pod 'CourierProtobuf', '0.0.5'
  pod 'ReachabilitySwift', '5.0.0'
  pod 'SwiftProtobuf'
end
